name: Python Virtual Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Create_Env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
